namespace dbc;

table module1_temps {
   module_voltage_1:float;
   module_voltage_2:float;
   module_voltage_3:float;
   module_voltage_4:float;
   module_voltage_5:float;
   module_voltage_6:float;
   module_voltage_7:float;
   module_voltage_8:float;
}

table module1_status {
   module_temperature:int32;
   module_firmware_is_dirty:bool;
   module_humidity:int32;
   module_code_on_main:bool;
   module_on_time_seconds:int32;
   module_firmware_version:int32;
}

table module2_temps {
   module_voltage_1:float;
   module_voltage_2:float;
   module_voltage_3:float;
   module_voltage_4:float;
   module_voltage_5:float;
   module_voltage_6:float;
   module_voltage_7:float;
   module_voltage_8:float;
}

table module2_status {
   module_temperature:int32;
   module_firmware_is_dirty:bool;
   module_humidity:int32;
   module_code_on_main:bool;
   module_on_time_seconds:int32;
   module_firmware_version:int32;
}

table module3_temps {
   module_voltage_1:float;
   module_voltage_2:float;
   module_voltage_3:float;
   module_voltage_4:float;
   module_voltage_5:float;
   module_voltage_6:float;
   module_voltage_7:float;
   module_voltage_8:float;
}

table module3_status {
   module_temperature:int32;
   module_firmware_is_dirty:bool;
   module_humidity:int32;
   module_code_on_main:bool;
   module_on_time_seconds:int32;
   module_firmware_version:int32;
}

table module4_temps {
   module_voltage_1:float;
   module_voltage_2:float;
   module_voltage_3:float;
   module_voltage_4:float;
   module_voltage_5:float;
   module_voltage_6:float;
   module_voltage_7:float;
   module_voltage_8:float;
}

table module4_status {
   module_temperature:int32;
   module_firmware_is_dirty:bool;
   module_humidity:int32;
   module_code_on_main:bool;
   module_on_time_seconds:int32;
   module_firmware_version:int32;
}

table module5_temps {
   module_voltage_1:float;
   module_voltage_2:float;
   module_voltage_3:float;
   module_voltage_4:float;
   module_voltage_5:float;
   module_voltage_6:float;
   module_voltage_7:float;
   module_voltage_8:float;
}

table module5_status {
   module_temperature:int32;
   module_firmware_is_dirty:bool;
   module_humidity:int32;
   module_code_on_main:bool;
   module_on_time_seconds:int32;
   module_firmware_version:int32;
}

table precharge_status {
   precharge_state:int32;
   precharge_accVoltageMod100:int32;
   precharge_accVoltageDiv100:int32;
   precharge_tsVoltageMod100:int32;
   precharge_tsVoltageDiv100:int32;
   precharge_errorCode:int32;
}

table vcu_status {
   VCU_IMD_OK_HIGH:bool;
   VCU_SHUTDOWN_B_OK_HIGH:bool;
   VCU_BMS_OK_HIGH:bool;
   VCU_SHUTDOWN_C_OK_HIGH:bool;
   VCU_BSPD_OK_HIGH:bool;
   VCU_SHUTDOWN_D_OK_HIGH:bool;
   VCU_SOFTWARE_OK_HIGH:bool;
   VCU_SHUTDOWN_E_OK_HIGH:bool;
   VCU_ACCEL_IMPLAUSIBLE:bool;
   VCU_BRAKE_IMPLAUSIBLE:bool;
   VCU_BRAKE_ACTIVE:bool;
   VCU_BSPD_CURRENT_HIGH:bool;
   VCU_BSPD_BRAKE_HIGH:bool;
   VCU_ACCEL_BRAKE_IMPLAUSIBLE:bool;
   VCU_STATEMACHINE_STATE:int32;
   VCU_INVERTER_POWERED:bool;
   VCU_ENERGY_METER_PRESENT:bool;
   VCU_ACTIVATE_BUZZER:bool;
   VCU_SOFTWARE_OK:bool;
   VCU_LAUNCH_CONTROL_ACTIVE:bool;
   VCU_MAX_TORQUE:int32;
   VCU_TORQUE_MODE:int32;
   VCU_DISTANCE_TRAVELLED:int32;
}

table vcu_pedal_readings {
   APPS1:int32;
   APPS2:int32;
   BSE1:int32;
   STEERING:int32;
}

table vcu_wheelspeed_readings {
   vcu_rpm_rear_left:int32;
   vcu_rpm_front_right:int32;
}

table vcu_pedal_threshold_settings {
   vcu_pedals_settings_MUX:int32;
   vcu_apps2_start_threshold:int32;
   vcu_apps1_end_threshold:int32;
   vcu_brake_active_threshold:int32;
   vcu_apps2_end_threshold:int32;
   vcu_apps1_ov_threshold:int32;
   vcu_apps1_uv_threshold:int32;
   vcu_apps2_ov_threshold:int32;
   vcu_apps2_uv_threshold:int32;
   vcu_apps1_start_threshold:int32;
}

table vcu_firmware_version {
   vcu_fw_version:int32;
   vcu_on_time_seconds:int32;
   vcu_project_on_main:bool;
   vcu_project_is_dirty:bool;
}

table vcu_board_readings_one {
   VCU_GLV_CURRENT:int32;
   VCU_GLV_VOLTAGE:int32;
   VCU_BSPD_VOLTAGE:int32;
   VCU_5V_VOLTAGE:int32;
}

table vcu_board_readings_two {
   VCU_SDC_VOLTAGE:int32;
   VCU_SDC_CURRENT:int32;
   VCU_AIN9_VOLTAGE:int32;
   VCU_AIN10_VOLTAGE:int32;
}

table vcu_pedals_travel {
   vcu_apps1_travel:float;
   vcu_apps2_travel:float;
   vcu_bse1_travel:float;
}

table vcu_launchcontrol_countdown {
   vcu_launchcontrol_release_countdown:int32;
   vcu_release_delay:int32;
}

table vcu_distance_tracker_motor {
   vcu_motor_energy_wh:float;
   vcu_motor_efficiency_instantaneous:float;
   vcu_motor_distance_meters:int32;
   vcu_motor_efficiency_kmkwh:float;
}

table vcu_distance_tracker_wheelspeed {
   vcu_wheelspeed_energy_wh:float;
   vcu_wheelspeed_efficiency_instantaneous:float;
   vcu_wheelspeed_distance_meters:int32;
   vcu_wheelspeed_efficiency_kmkwh:float;
}

table vcu_lifetime_distance_and_ontime {
   vcu_lifetime_ontime:int32;
   vcu_lifetime_distance:int32;
}

table vcu_distance_tracker_vectornav {
   vcu_vectornav_energy_wh:float;
   vcu_vectornav_efficiency_instantaneous:float;
   vcu_vectornav_distance_meters:int32;
   vcu_vectornav_efficiency_kmkwh:float;
}

table vcu_coulomb_counters {
   vcu_wsfl_ah:float;
   vcu_motor_ah:float;
   vcu_vnav_ah:float;
}

table vcu_calculated_slip {
   vcu_front_rpm_avg:float;
   vcu_rear_rpm_avg:float;
}

table vcu_set_parameter {
   vcu_target_parameter:int32;
   vcu_parameter_value:int32;
}

table dash_buttons {
   dash_button1status:bool;
   dash_button2status:bool;
   dash_button3status:bool;
   dash_button4status:bool;
   dash_button5status:bool;
   dash_button6status:bool;
}

table dash_firmware_version {
   dash_fw_version:int32;
   dash_on_time_seconds:int32;
   dash_project_on_main:bool;
   dash_project_is_dirty:bool;
}

table evelogger_vectornav_time {
   vectornav_time:uint64;
}

table evelogger_vectornav_attitude {
   evelogger_vectornav_yaw:float;
   evelogger_vectornav_roll:float;
   evelogger_vectornav_pitch:float;
}

table evelogger_vectornav_gyro {
   evelogger_vectornav_W_x:float;
   evelogger_vectornav_W_y:float;
   evelogger_vectornav_W_z:float;
}

table evelogger_vectornav_position {
   evelogger_vectornav_latitude:float;
   evelogger_vectornav_longitude:float;
}

table evelogger_vectornav_velocity {
   evelogger_vectornav_v_n:float;
   evelogger_vectornav_v_e:float;
   evelogger_vectornav_v_d:float;
}

table evelogger_vectornav_acceleration {
   evelogger_vectornav_accelX:float;
   evelogger_vectornav_accelY:float;
   evelogger_vectornav_accelZ:float;
}

table acu_shutdown_status {
   acu_imd_relay_state:bool;
   acu_bms_relay_state:bool;
   acu_imd_gpio_state:bool;
   acu_bms_gpio_state:bool;
   acu_imd_pwm_frequency:int32;
   acu_imd_pwm_duty:int32;
}

table acu_board_voltage_readings {
   acu_sdc_voltage:float;
   acu_sdc_current:float;
   acu_glv_voltage:float;
   acu_glv_current:float;
   acu_5v_voltage:float;
   acu_3v_voltage:float;
}

table acu_firmware_version {
   acu_temperature:int32;
   acu_firmware_is_dirty:bool;
   acu_humidity:int32;
   acu_code_on_main:bool;
   acu_on_time_seconds:int32;
   firmware_version:int32;
}

table cornernode_steeringpot {
   steeringpot:int32;
}

table cornernode_fl_shockpot {
   shockpot:int32;
}

table cornernode_fr_shockpot {
   shockpot:int32;
}

table cornernode_rl_shockpot {
   shockpot:int32;
}

table cornernode_rr_shockpot {
   shockpot:int32;
}

table cornernode_fl_wheelspeed {
   wheelspeed:int32;
}

table cornernode_fr_wheelspeed {
   wheelspeed:int32;
}

table cornernode_rl_wheelspeed {
   wheelspeed:int32;
}

table cornernode_rr_wheelspeed {
   wheelspeed:int32;
}

table cornernode_fl_tiretemp {
   tiretemp:uint64;
}

table cornernode_fr_tiretemp {
   tiretemp:uint64;
}

table cornernode_rl_tiretemp {
   tiretemp:uint64;
}

table cornernode_rr_tiretemp {
   tiretemp:uint64;
}

table cornernode_front_brakepressure {
   brakepressure:int32;
}

table cornernode_rear_brakepressure {
   brakepressure:int32;
}

table cornernode_motor_temp {
   motor_temp:float;
}

table cornernode_coolant_temp {
   coolant_temp:float;
}

table msgid_0x6b1 {
   Pack_Current:float;
   Pack_Inst_Voltage:float;
   Pack_Open_Voltage:float;
   Pack_Summed_Voltage:float;
}

table msgid_0x6b2 {
   High_Temperature:int32;
   Low_Temperature:int32;
   Average_Temperature:int32;
   Avg_Cell_Voltage:float;
   Low_Cell_Voltage:float;
}

table msgid_0x6b3 {
   Pack_SOC:float;
}

table msgid_0x6b4 {
   DTC_P0AA6_High_Voltage_Isolation_Fault:bool;
}

table msgid_0x1806e7f4 {
   Maximum_Pack_Voltage:float;
   Pack_CCL:float;
   DTC_P0A08_Charger_Safety_Relay_Fault:bool;
}

table msgid_0x1806e5f4 {
   Maximum_Pack_Voltage:float;
   Pack_CCL:float;
   DTC_P0A08_Charger_Safety_Relay_Fault:bool;
}

table msgid_0x1806e9f4 {
   Maximum_Pack_Voltage:float;
   Pack_CCL:float;
   DTC_P0A08_Charger_Safety_Relay_Fault:bool;
}

table m173_modulation_and_flux_info {
   INV_Modulation_Index:float;
   INV_Flux_Weakening_Output:float;
   INV_Id_Command:float;
   INV_Iq_Command:float;
}

table m172_torque_and_timer_info {
   INV_Commanded_Torque:float;
   INV_Torque_Feedback:float;
   INV_Power_On_Timer:float;
}

table m194_read_write_param_response {
   INV_Parameter_Response_Addr:int32;
   INV_Parameter_Response_Write_OK:bool;
   INV_Parameter_Response_Data:int32;
}

table m193_read_write_param_command {
   VCU_INV_Parameter_Address:int32;
   VCU_INV_Parameter_RW_Command:bool;
   VCU_INV_Parameter_Data:int32;
}

table m192_command_message {
   VCU_INV_Torque_Command:float;
   VCU_INV_Speed_Command:int32;
   VCU_INV_Direction_Command:string;
   VCU_INV_Inverter_Enable:string;
   VCU_INV_Inverter_Discharge:string;
   VCU_INV_Speed_Mode_Enable:bool;
   VCU_INV_Rolling_Counter:int32;
   VCU_INV_Torque_Limit_Command:float;
}

table m171_fault_codes {
   INV_Post_Fault_Lo:int32;
   INV_Post_Fault_Hi:int32;
   INV_Run_Fault_Lo:int32;
   INV_Run_Fault_Hi:int32;
}

table m170_internal_states {
   INV_VSM_State:string;
   INV_PWM_Frequency:int32;
   INV_Inverter_State:string;
   INV_Relay_1_Status:bool;
   INV_Relay_2_Status:bool;
   INV_Relay_3_Status:bool;
   INV_Relay_4_Status:bool;
   INV_Relay_5_Status:bool;
   INV_Relay_6_Status:bool;
   INV_Inverter_Run_Mode:bool;
   INV_Self_Sensing_Assist_Enable:bool;
   INV_Inverter_Discharge_State:string;
   INV_Inverter_Command_Mode:bool;
   INV_Rolling_Counter:int32;
   INV_Inverter_Enable_State:bool;
   INV_Burst_Model_Mode:string;
   INV_BMS_Limiting_Regen_Torque:bool;
   INV_Key_Switch_Start_Status:bool;
   INV_Inverter_Enable_Lockout:bool;
   INV_Direction_Command:bool;
   INV_BMS_Active:bool;
   INV_BMS_Limiting_Motor_Torque:bool;
   INV_Limit_Max_Speed:bool;
   INV_Limit_Hot_Spot:bool;
   INV_Low_Speed_Limiting:bool;
   INV_Limit_Coolant_Derating:bool;
   INV_Limit_Stall_Burst_Model:string;
}

table m169_internal_voltages {
   INV_Ref_Voltage_1_5:float;
   INV_Ref_Voltage_2_5:float;
   INV_Ref_Voltage_5_0:float;
   INV_Ref_Voltage_12_0:float;
}

table m168_flux_id_iq_info {
   INV_Vd_ff:float;
   INV_Vq_ff:float;
   INV_Id:float;
   INV_Iq:float;
}

table m167_voltage_info {
   INV_DC_Bus_Voltage:float;
   INV_Output_Voltage:float;
   INV_VAB_Vd_Voltage:float;
   INV_VBC_Vq_Voltage:float;
}

table m166_current_info {
   INV_Phase_A_Current:float;
   INV_Phase_B_Current:float;
   INV_Phase_C_Current:float;
   INV_DC_Bus_Current:float;
}

table m165_motor_position_info {
   INV_Motor_Angle_Electrical:float;
   INV_Motor_Speed:int32;
   INV_Electrical_Output_Frequency:float;
   INV_Delta_Resolver_Filtered:float;
}

table m164_digital_input_status {
   INV_Digital_Input_1:bool;
   INV_Digital_Input_2:bool;
   INV_Digital_Input_3:bool;
   INV_Digital_Input_4:bool;
   INV_Digital_Input_5:bool;
   INV_Digital_Input_6:bool;
   INV_Digital_Input_7:bool;
   INV_Digital_Input_8:bool;
}

table m163_analog_input_voltages {
   INV_Analog_Input_1:float;
   INV_Analog_Input_2:float;
   INV_Analog_Input_3:float;
   INV_Analog_Input_4:float;
   INV_Analog_Input_5:float;
   INV_Analog_Input_6:float;
}

table m162_temperature_set_3 {
   INV_Coolant_Temp:float;
   INV_Hot_Spot_Temp:float;
   INV_Motor_Temp:float;
   INV_Torque_Shudder:float;
}

table m161_temperature_set_2 {
   INV_Control_Board_Temp:float;
   INV_RTD1_Temperature:float;
   INV_RTD2_Temperature:float;
   INV_Stall_Burst_Model_Temp:float;
}

table m160_temperature_set_1 {
   INV_Module_A_Temp:float;
   INV_Module_B_Temp:float;
   INV_Module_C_Temp:float;
   INV_Gate_Driver_Board_Temp:float;
}

table m174_firmware_info {
   INV_Project_Code_EEP_Ver:int32;
   INV_SW_Version:int32;
   INV_DateCode_MMDD:int32;
   INV_DateCode_YYYY:int32;
}

table m175_diag_data_message {
   INV_Diag_Record:int32;
   INV_Diag_Segment:int32;
   INV_Diag_PWM_Freq:int32;
   INV_Diag_Vq_Cmd:float;
   INV_Diag_Id_cmd:float;
   INV_Diag_Ic:float;
   INV_Diag_Cos_Used:int32;
   INV_Diag_Gamma_Resolver:float;
   INV_Diag_Run_Faults_Lo:int32;
   INV_Diag_Vd_Cmd:float;
   INV_Diag_Mod_Index:float;
   INV_Diag_Vdc:float;
   INV_Diag_Ia:float;
   INV_Diag_Gamma_Observer:float;
   INV_Diag_Run_Faults_Hi:int32;
   INV_Diag_Vqs_Cmd:float;
   INV_Diag_FW_Output:float;
   INV_Diag_Iq_cmd:float;
   INV_Diag_Ib:float;
   INV_Diag_Sin_Used:int32;
}

table bms_current_limit {
   BMS_Max_Discharge_Current:int32;
   BMS_Max_Charge_Current:int32;
}

table m176_fast_info {
   INV_Fast_Torque_Command:float;
   INV_Fast_Torque_Feedback:float;
   INV_Fast_Motor_Speed:int32;
   INV_Fast_DC_Bus_Voltage:float;
}

table m177_torque_capability {
   INV_Torque_Capability_Motor:float;
   INV_Torque_Capability_Regen:float;
}

table status {
   OutputVoltage:float;
   OutputCurrent:float;
   HWStatus:string;
   Temperature:string;
   InputVoltage:string;
   State:string;
   CommunicationState:string;
}

