use clap::{Arg, ArgAction, Command};
use std::time::{SystemTime, UNIX_EPOCH};

static DATE_TIME_FORMAT: &str = "%Y-%m-%d_%H:%M:%S";

#[derive(Debug, Clone, Copy)]
pub enum LoggerType {
    Can,
    Audio,
    Video,
    // Gopro,
}

impl LoggerType {
    pub fn arg_name(&self) -> &'static str {
        match self {
            LoggerType::Can => "can",
            LoggerType::Audio => "audio",
            LoggerType::Video => "video",
            // LoggerType::Gopro => "gopro",
        }
    }

    fn arg_name_short(&self) -> char {
        match self {
            LoggerType::Can => 'C',
            LoggerType::Audio => 'A',
            LoggerType::Video => 'V',
            // LoggerType::Gopro => 'G',
        }
    }

    pub fn all() -> &'static [LoggerType] {
        &[
            LoggerType::Can,
            LoggerType::Audio,
            LoggerType::Video,
            // LoggerType::Gopro,
        ]
    }

    pub fn evaluate_args() -> clap::ArgMatches {
        LoggerType::add_args(
            Command::new("foxglove-bridge")
            .about("Start a CAN logger with: DEVICE[:FILE]\tAn example is -C can0 for adding can0 to the global log, -C pipe1:race.mcap for a unique log file for can1 with the name race.mcap, -C can0: for a unique log with an autogenerated name")
        )
        .get_matches()
    }

    fn add_args(cmd: Command) -> Command {
        LoggerType::all()
            .iter()
            .fold(cmd, |cmd, logger| match logger {
                LoggerType::Can => cmd.arg(
                    Arg::new(logger.arg_name())
                        .short(logger.arg_name_short())
                        .help("Requires SocketCAN device")
                        .num_args(1)
                        .action(ArgAction::Append)
                        .value_name("DEVICE[:FILE]"),
                ),
                LoggerType::Audio => cmd.arg(
                    Arg::new(logger.arg_name())
                        .short(logger.arg_name_short())
                        .help("Requires pipewire device")
                        .num_args(1)
                        .action(ArgAction::Append)
                        .value_name("DEVICE[:FILE]"),
                ),
                LoggerType::Video => cmd.arg(
                    Arg::new(logger.arg_name())
                        .short(logger.arg_name_short())
                        .help("Requires v4l2 device")
                        .num_args(1)
                        .action(ArgAction::Append)
                        .value_name("DEVICE[:FILE]"),
                ),
                // LoggerType::Gopro => cmd.arg(
                //     Arg::new(logger.arg_name())
                //         .short(logger.arg_name_short())
                //         .help("Requires connected and configured GoPro")
                //         .num_args(1)
                //         .action(ArgAction::Append)
                //         .value_name("DEVICE[:FILE]"),
                // ),
            })
    }
}

pub fn pretty_print_system_time() -> String {
    let now = SystemTime::now();
    let duration = now.duration_since(UNIX_EPOCH).expect("Time is being funny");

    let datetime = chrono::DateTime::<chrono::Local>::from(UNIX_EPOCH + duration);
    datetime.format(DATE_TIME_FORMAT).to_string()
}

pub fn parse_device_file(input: &str, key: &str) -> (String, Option<String>) {
    let mut parts = input.splitn(2, ':');
    let device = parts.next().unwrap().to_string();
    let file = parts.next().map(|s| {
        if s.is_empty() {
            format!("{}_{}", key.to_uppercase(), pretty_print_system_time())
        } else {
            s.to_string()
        }
    });

    (device, file)
}
